### ISSUE TITLE
how to subscribe the web socket?

### ISSUE THREAD

**Issue by tonyshare** [lamisChebbi/ng-realtime-dashboard#9]
The webSocket must be subscribe, than the program will make a real web socket  connection to the server,
but in data service file,  the `socket$` variable is defined to be private, how to make subscribe with the  `DataService`?

```
export class DataService {

  private socket$;
  private messagesSubject$ = new Subject();
  public messages$ = this.messagesSubject$.pipe(switchAll(), catchError(e => { throw e }));

  constructor() {
  }

  /**
   * Creates a new WebSocket subject and send it to the messages subject
   * @param cfg if true the observable will be retried.
   */
  public connect(cfg: { reconnect: boolean } = { reconnect: false }): void {

    if (!this.socket$ || this.socket$.closed) {
      this.socket$ = this.getNewWebSocket();
      const messages = this.socket$.pipe(cfg.reconnect ? this.reconnect : o => o,
        tap({
          error: error => console.log(error),
        }), catchError(_ => EMPTY))
      //toDO only next an observable if a new subscription was made double-check this
      this.messagesSubject$.next(messages);
    }
  }

  /**
   * Retry a given observable by a time span
   * @param observable the observable to be retried
   */
  private reconnect(observable: Observable<any>): Observable<any> {
    return observable.pipe(retryWhen(errors => errors.pipe(tap(val => console.log('[Data Service] Try to reconnect', val)),
      delayWhen(_ => timer(RECONNECT_INTERVAL)))));
  }

  close() {
    this.socket$.complete();
    this.socket$ = undefined;
  }

  sendMessage(msg: any) {
    this.socket$.next(msg);
  }

  /**
   * Return a custom WebSocket subject which reconnects after failure
   */
  private getNewWebSocket() {
    return webSocket({
      url: WS_ENDPOINT,
      openObserver: {
        next: () => {
          console.log('[DataService]: connection ok');
        }
      },
      closeObserver: {
        next: () => {
          console.log('[DataService]: connection closed');
          this.socket$ = undefined;
          this.connect({ reconnect: true });
        }
      },

    });
  }

}
```

**Comment by stefangaller** [comment]
I've got the same question. How can this code work, without using `.subscribe()`?

**Comment by stefangaller** [comment]
@tonyshare I figured out what my problem was: 
1. The `subscribe()` function is not needed if you use the `AsyncPipe`.  
2. I called `connect()` in the constructor, before the View subscribed to the Observable. It needs to be the other way round, so using `ngAfterViewInit` as in the example did the trick for me.

Hope that helps :)

**Comment by lamisChebbi** [comment]
Hi @tonyshare  @stefangaller 

The subscription should be managed inside the "Real Time" component. In the case of this library, it inside the 
live-table.component.ts

Step 1 :  I'm calling the connect method in order to create the RxJsWebSocket Subject
`  ngAfterViewInit() {
    this.service.connect();
  }`
  
The socket$ is used internally inside the DataService it shouldn't be public to secure the consumption of sockets. The messages$ instead is the public observable that will emit the real updates, so Step 2 
Process this observable, in my case it is the transactions$ in live-table.component.ts if you need to do some custom transformation. If not juste use this.service.messages$ directly 

Step3: Subscribe to it ! 
And it is done using the async pipe in the HTML file. 

Hope this helps and it is clear ! 

Thank you :)
